# Generated by Django 3.2.16 on 2022-10-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('area_de_conhecimento', models.CharField(max_length=250)),
                ('nivel', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None)),
                ('aplicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startrack.pessoa')),
            ],
            options={
                'verbose_name': 'Selo',
                'verbose_name_plural': 'Selos',
            },
        ),
    ]
